run:
  tests: true

linters-settings:
  funlen:
    lines: 150
    statements: 80
  gci:
    sections:
      - standard
      - default
      - blank
      - dot
    skip-generated: true
    custom-order: true
  depguard:
    rules:
      main:
        files:
          - "$all"
        allow:
          - "$gostd"
          - "github.com/kelseyhightower/envconfig"
          - "github.com/subosito/gotenv"
          - "rate_limiter/pb"
          - "rate_limiter/config"
          - "github.com/jackc/pgx/v5/stdlib"
          - "rate_limiter/internal/app/bucket"
          - "rate_limiter/internal/app/cache"
          - "rate_limiter/internal/app/repository"
          - "github.com/golang/protobuf/ptypes/empty"
          - "rate_limiter/internal/app/service"
          - "github.com/stretchr/testify/require"
          - "github.com/stretchr/testify/mock"

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace